this addaction ["Platoon Leader", "loadouts\us_pl.sqf"];
this addaction ["Platoon FAC", "loadouts\us_p_fac.sqf"];
this addaction ["Platoon Engineer (Demo)", "loadouts\us_p_e_demo.sqf"];
this addaction ["Platoon Engineer (EOD)", "loadouts\us_p_e_eod.sqf"];
this addaction ["Platoon Engineer (Fortification)", "loadouts\us_p_e_fort.sqf"];
this addaction ["Platoon Engineer (Repair)", "loadouts\us_p_e_rep.sqf"];
this addaction ["Platoon DMR", "loadouts\us_p_dmr.sqf"];
this addaction ["Platoon Driver", "loadouts\us_p_d.sqf"];
this addaction ["Platoon AR", "loadouts\us_p_ar.sqf"];
this addaction ["Platoon Medic", "loadouts\us_p_medic.sqf"];
this addaction ["Squad Leader", "loadouts\us_sl.sqf"];
this addaction ["Combat Medic", "loadouts\us_medic.sqf"];
this addaction ["Operator Rifle", "loadouts\us_o_r.sqf"];
this addaction ["Operator AR", "loadouts\us_o_ar.sqf"];
this addaction ["Operator Light AT", "loadouts\us_o_lat.sqf"];
this addaction ["Operator MMG", "loadouts\us_o_mmg.sqf"];
this addaction ["Operator Asst. MMG", "loadouts\us_o_mmg_ab.sqf"];
this addaction ["Operator Medium AT", "loadouts\us_o_mat.sqf"];
this addaction ["Operator Asst. Medium AT", "loadouts\us_o_mat_ab.sqf"];
this addaction ["Operator Grenadier", "loadouts\us_o_g.sqf"];
this addaction ["Operator DMR (5.56)", "loadouts\us_o_dmr.sqf"];
this addaction ["Operator Battlerifle (M14)", "loadouts\us_o_br.sqf"];
this addaction ["Operator Specialist (M4A1)", "loadouts\us_o_spc.sqf"];
this addaction ["Operator Breacher", "loadouts\us_o_breacher.sqf"];
this addaction ["Operator Engineer (Demo)", "loadouts\us_o_e_demo.sqf"];
this addaction ["Operator Engineer (EOD)", "loadouts\us_o_e_eod.sqf"];
this addaction ["Operator Engineer (Fortification)", "loadouts\us_o_e_fort.sqf"];
this addaction ["Operator Engineer (Repair)", "loadouts\us_o_e_rep.sqf"];
this addaction ["Echo Rifleman", "loadouts\us_e_r.sqf"];
this addaction ["Echo AR", "loadouts\us_e_ar.sqf"];
this addaction ["Echo Engineer (Demo)", "loadouts\us_e_e_demo.sqf"];
this addaction ["Echo Engineer (EOD)", "loadouts\us_e_e_eod.sqf"];
this addaction ["Echo Engineer (Fortification)", "loadouts\us_e_e_fort.sqf"];
this addaction ["Echo Engineer (Repair)", "loadouts\us_e_e_rep.sqf"];
this addaction ["Echo Heavy Weapons (Mortar)", "loadouts\us_e_mor.sqf"];
this addaction ["Echo Asst. Heavy Weapons (Mortar)", "loadouts\us_e_mor_ab.sqf"];
this addaction ["Echo Heavy Weapons (HAT)", "loadouts\us_e_hat.sqf"];
this addaction ["Echo Asst. Heavy Weapons (HAT)", "loadouts\us_e_hat_ab.sqf"];
this addaction ["Echo Driver", "loadouts\us_e_d.sqf"];
this addaction ["Fox Commander", "loadouts\us_f_com.sqf"];
this addaction ["Fox Crewman", "loadouts\us_f_crew.sqf"];
this addaction ["Fox Technician", "loadouts\us_f_tech.sqf"];
this addaction ["Sierra Spotter", "loadouts\us_s_spotter.sqf"];
this addaction ["Sierra Sniper (M40A5)", "loadouts\us_s_sniper.sqf"];
this addaction ["Sierra Sniper (M107)", "loadouts\us_s_sniper_m107.sqf"];
this addaction ["Sierra Recon", "loadouts\us_s_recon.sqf"];
this addaction ["Rodeo Pilot", "loadouts\pilot_rotaryPilot.sqf"];
this addaction ["Rodeo Co-Pilot (Crewman)", "loadouts\pilot_rotaryPilot.sqf"];
this addaction ["Whiskey Pilot", "loadouts\pilot_fixedWing.sqf"];
this addaction ["<t color=""#0000FF"">" +"Save Loadout", {(_this select 1) setVariable ["SR_Loadout",getUnitLoadout (_this select 1)];}];
this addaction ["<t color=""#0000FF"">" +"Load Loadout", {(_this select 1)  setUnitLoadout ((_this select 1)  getVariable ["SR_Loadout",[]]);}];
