if(isServer) then {
	clearweaponcargoGlobal this;
	clearmagazinecargoGlobal this;
	clearitemcargoGlobal this;
	clearBackpackCargoGlobal this;
	this addmagazinecargoGlobal ["rhs_30Rnd_545x39_7N10_plum_AK", 72];
	this addmagazinecargoGlobal ["rhs_30Rnd_545x39_7N10_plum_AK", 12];
	this addmagazinecargoGlobal ["rhs_mag_9x18_8_57N181S", 16];
	this addmagazinecargoGlobal ["rhs_60Rnd_545X39_7N10_AK", 12];
	this addmagazinecargoGlobal ["rhs_100Rnd_762x54mmR", 8];
	this addmagazinecargoGlobal ["ACE_2Rnd_12Gauge_Pellets_No4_Buck", 20];
	this addmagazinecargoGlobal ["2Rnd_12Gauge_Slug", 20];
	this addmagazinecargoGlobal ["rhssaf_30Rnd_762x39mm_M67", 10];
	this addmagazinecargoGlobal ["rhssaf_30Rnd_762x39mm_M67", 16];
	this addmagazinecargoGlobal ["rhs_rpg7_PG7VL_mag", 5];
	this addmagazinecargoGlobal ["rhs_rpg7_PG7VR_mag", 1];
	this addmagazinecargoGlobal ["rhs_rpg7_OG7V_mag", 2];
	this addWeaponcargoGlobal ["rhs_weap_rpg18", 4];
	this addWeaponcargoGlobal ["rhs_weap_rshg2", 2];
	this additemcargoGlobal ["rhs_mag_f1", 8];
	this additemcargoGlobal ["rhs_grenade_khattabka_vog17_mag", 2];
	this additemcargoGlobal ["rhs_mag_rdg2_white", 28];
	this additemcargoGlobal ["rhs_mag_nspn_green", 2];
	this additemcargoGlobal ["rhs_mag_nspn_red", 2];
	this additemcargoGlobal ["rhs_mag_nspd", 2];
	this additemcargoGlobal ["SR_HE_Pack", 4];
	this additemcargoGlobal ["SR_Smoke_Pack", 4];
	this additemcargoGlobal ["SR_Flare_Pack", 4];
	this additemcargoGlobal ["rhs_mag_plamyam", 10];
	this additemcargoGlobal ["SatchelCharge_Remote_Mag", 2];
	this additemcargoGlobal ["rhs_ec400_mag", 4];
	this additemcargoGlobal ["rhs_mine_tm62m_mag", 4];
	this additemcargoGlobal ["APERSTripMine_Wire_Mag", 4];
	this additemcargoGlobal ["ACE_CableTie", 24];
	this addItemCargoGlobal ["SR_PAK", 10];
	this addItemCargoGlobal ["SR_Bandage_Pack", 5];
	this addItemCargoGlobal ["SR_Medicine_Pack", 5];
	this addItemCargoGlobal ["SR_BloodIV_Pack", 5];
	if (isNil "SR_Night") then {SR_Night = false};
    if (SR_Night) then {
    this addItemCargoGlobal ["ACE_IR_Strobe_Item", 50];
    };
};