if(isServer) then {
	clearweaponcargoGlobal this;
	clearmagazinecargoGlobal this;
	clearitemcargoGlobal this;
	clearBackpackCargoGlobal this;
	this addItemCargoGlobal ["rhsgref_5Rnd_792x57_kar98k",12];
	this addItemCargoGlobal ["uk3cb_PPSH_71rnd_magazine_G",3];
	this addItemCargoGlobal ["SR_PAK", 6];
	this addItemCargoGlobal ["ACE_epinephrine", 4];
	this addmagazinecargoGlobal ["rhs_mag_9x18_8_57N181S", 8];
	this additemcargoGlobal ["rhs_mag_rgd5", 4];
	this additemcargoGlobal ["rhs_mag_rgn", 2];
	this additemcargoGlobal ["rhs_mag_rdg2_white", 8];
	this additemcargoGlobal ["rhs_grenade_khattabka_vog17_mag", 4];
	this additemcargoGlobal ["rhs_mag_nspd", 4];
	this additemcargoGlobal ["SatchelCharge_Remote_Mag", 1];
	this additemcargoGlobal ["rhs_ec400_mag", 2];
	this additemcargoGlobal ["rhs_mine_tm62m_mag", 2];
	this additemcargoGlobal ["APERSTripMine_Wire_Mag", 2];
};