this addaction ["Platoon Leader", "loadouts\us_army_pl.sqf"];
this addaction ["Platoon FAC", "loadouts\us_army_p_fac.sqf"];
this addaction ["Platoon Engineer (Demo)", "loadouts\us_army_p_e_demo.sqf"];
this addaction ["Platoon Engineer (EOD)", "loadouts\us_army_p_e_eod.sqf"];
this addaction ["Platoon Engineer (Fortification)", "loadouts\us_army_p_e_fort.sqf"];
this addaction ["Platoon Engineer (Repair)", "loadouts\us_army_p_e_rep.sqf"];
this addaction ["Platoon DMR", "loadouts\us_army_p_dmr.sqf"];
this addaction ["Platoon AR", "loadouts\us_army_p_ar.sqf"];
this addaction ["Platoon Medic", "loadouts\us_army_p_medic.sqf"];
this addaction ["Squad Leader", "loadouts\us_army_sl.sqf"];
this addaction ["Combat Medic", "loadouts\us_army_medic.sqf"];
this addaction ["Operator AR", "loadouts\us_army_o_ar.sqf"];
this addaction ["Operator Light AT", "loadouts\us_army_o_lat.sqf"];
this addaction ["Operator MMG", "loadouts\us_army_o_mmg.sqf"];
this addaction ["Operator Asst. MMG", "loadouts\us_army_o_mmg_ab.sqf"];
this addaction ["Operator Medium AT", "loadouts\us_army_o_mat.sqf"];
this addaction ["Operator Asst. Medium AT", "loadouts\us_army_o_mat_ab.sqf"];
this addaction ["Operator Grenadier", "loadouts\us_army_o_g.sqf"];
this addaction ["Operator DMR", "loadouts\us_army_o_dmr.sqf"];
this addaction ["Operator Battlerifle (M1918 BAR)", "loadouts\us_army_o_br.sqf"];
this addaction ["Operator Specialist", "loadouts\us_army_o_spc.sqf"];
this addaction ["Operator Breacher", "loadouts\us_army_o_breacher.sqf"];
this addaction ["Operator Engineer (Demo)", "loadouts\us_army_o_e_demo.sqf"];
this addaction ["Operator Engineer (EOD)", "loadouts\us_army_o_e_eod.sqf"];
this addaction ["Operator Engineer (Fortification)", "loadouts\us_army_o_e_fort.sqf"];
this addaction ["Operator Engineer (Repair)", "loadouts\us_army_o_e_rep.sqf"];
this addaction ["Echo Rifleman", "loadouts\us_army_e_r.sqf"];
this addaction ["Echo AR", "loadouts\us_army_e_ar.sqf"];
this addaction ["Echo Engineer (Demo)", "loadouts\us_army_e_e_demo.sqf"];
this addaction ["Echo Engineer (EOD)", "loadouts\us_army_e_e_eod.sqf"];
this addaction ["Echo Engineer (Fortification)", "loadouts\us_army_e_e_fort.sqf"];
this addaction ["Echo Engineer (Repair)", "loadouts\us_army_e_e_rep.sqf"];
this addaction ["Echo Heavy Weapons (Mortar)", "loadouts\us_army_e_mor.sqf"];
this addaction ["Echo Asst. Heavy Weapons (Mortar)", "loadouts\us_army_e_mor_ab.sqf"];
this addaction ["Fox Commander", "loadouts\us_army_f_com.sqf"];
this addaction ["Fox Crewman", "loadouts\us_army_f_crew.sqf"];
this addaction ["Fox Technician", "loadouts\us_army_f_tech.sqf"];
this addaction ["Rodeo Pilot", "loadouts\usmc_pilot_rotaryPilot.sqf"];
this addaction ["Rodeo Co-Pilot (Crewman)", "loadouts\usmc_pilot_rotaryPilot.sqf"];
this addaction ["Whiskey Pilot", "loadouts\usaf_pilot_fixedWing.sqf"];
this addaction ["<t color=""#0000FF"">" +"Save Loadout", {(_this select 1) setVariable ["SR_Loadout",getUnitLoadout (_this select 1)];}];
this addaction ["<t color=""#0000FF"">" +"Load Loadout", {(_this select 1)  setUnitLoadout ((_this select 1)  getVariable ["SR_Loadout",[]]);}];
