this addaction ["Platoon Leader", "loadouts\irn_pl.sqf"];
this addaction ["Platoon FAC", "loadouts\irn_p_fac.sqf"];
this addaction ["Platoon Engineer (Demo)", "loadouts\irn_p_e_demo.sqf"];
this addaction ["Platoon Engineer (EOD)", "loadouts\irn_p_e_eod.sqf"];
this addaction ["Platoon Engineer (Fortification)", "loadouts\irn_p_e_fort.sqf"];
this addaction ["Platoon Engineer (Repair)", "loadouts\irn_p_e_rep.sqf"];
this addaction ["Platoon DMR", "loadouts\irn_p_dmr.sqf"];
this addaction ["Platoon Driver", "loadouts\irn_p_d.sqf"];
this addaction ["Platoon AR", "loadouts\irn_p_ar.sqf"];
this addaction ["Platoon Medic", "loadouts\irn_p_medic.sqf"];
this addaction ["Squad Leader", "loadouts\irn_sl.sqf"];
this addaction ["Combat Medic", "loadouts\irn_medic.sqf"];
this addaction ["Operator Rifle", "loadouts\irn_o_r.sqf"];
this addaction ["Operator AR", "loadouts\irn_o_ar.sqf"];
this addaction ["Operator Light AT", "loadouts\irn_o_lat.sqf"];
this addaction ["Operator MMG", "loadouts\irn_o_mmg.sqf"];
this addaction ["Operator Asst. MMG", "loadouts\irn_o_mmg_ab.sqf"];
this addaction ["Operator Medium AT", "loadouts\irn_o_mat.sqf"];
this addaction ["Operator Asst. Medium AT", "loadouts\irn_o_mat_ab.sqf"];
this addaction ["Operator Grenadier", "loadouts\irn_o_g.sqf"];
this addaction ["Operator DMR ", "loadouts\irn_o_dmr.sqf"];
this addaction ["Operator Battlerifle ", "loadouts\irn_o_br.sqf"];
this addaction ["Operator Specialist ", "loadouts\irn_o_spc.sqf"];
this addaction ["Operator Breacher", "loadouts\irn_o_breacher.sqf"];
this addaction ["Operator Engineer (Demo)", "loadouts\irn_o_e_demo.sqf"];
this addaction ["Operator Engineer (EOD)", "loadouts\irn_o_e_eod.sqf"];
this addaction ["Operator Engineer (Fortification)", "loadouts\irn_o_e_fort.sqf"];
this addaction ["Operator Engineer (Repair)", "loadouts\irn_o_e_rep.sqf"];
this addaction ["Echo Rifleman", "loadouts\irn_e_r.sqf"];
this addaction ["Echo AR", "loadouts\irn_e_ar.sqf"];
this addaction ["Echo Engineer (Demo)", "loadouts\irn_e_e_demo.sqf"];
this addaction ["Echo Engineer (EOD)", "loadouts\irn_e_e_eod.sqf"];
this addaction ["Echo Engineer (Fortification)", "loadouts\irn_e_e_fort.sqf"];
this addaction ["Echo Engineer (Repair)", "loadouts\irn_e_e_rep.sqf"];
this addaction ["Echo Heavy Weapons (Mortar)", "loadouts\irn_e_mor.sqf"];
this addaction ["Echo Asst. Heavy Weapons (Mortar)", "loadouts\irn_e_mor_ab.sqf"];
this addaction ["Echo Heavy Weapons (HAT)", "loadouts\irn_e_hat.sqf"];
this addaction ["Echo Asst. Heavy Weapons (HAT)", "loadouts\irn_e_hat_ab.sqf"];
this addaction ["Echo Driver", "loadouts\irn_e_d.sqf"];
this addaction ["Fox Commander", "loadouts\irn_f_com.sqf"];
this addaction ["Fox Crewman", "loadouts\irn_f_crew.sqf"];
this addaction ["Fox Technician", "loadouts\irn_f_tech.sqf"];
this addaction ["Sierra Spotter", "loadouts\irn_s_spotter.sqf"];
this addaction ["Sierra Sniper", "loadouts\irn_s_sniper.sqf"];
this addaction ["Sierra Recon", "loadouts\irn_s_recon.sqf"];
this addaction ["Rodeo Pilot", "loadouts\pilot_rotaryPilot.sqf"];
this addaction ["Rodeo Co-Pilot (Crewman)", "loadouts\pilot_rotaryPilot.sqf"];
this addaction ["<t color=""#0000FF"">" +"Save Loadout", {(_this select 1) setVariable ["SR_Loadout",getUnitLoadout (_this select 1)];}];
this addaction ["<t color=""#0000FF"">" +"Load Loadout", {(_this select 1)  setUnitLoadout ((_this select 1)  getVariable ["SR_Loadout",[]]);}];
