this addaction ["Platoon Leader", "loadouts\ctrg_arid_pl.sqf"];
this addaction ["Platoon FAC", "loadouts\ctrg_arid_p_fac.sqf"];
this addaction ["Platoon Engineer (Demo)", "loadouts\ctrg_arid_p_e_demo.sqf"];
this addaction ["Platoon Engineer (EOD)", "loadouts\ctrg_arid_p_e_eod.sqf"];
this addaction ["Platoon Engineer (Fortification)", "loadouts\ctrg_arid_p_e_fort.sqf"];
this addaction ["Platoon Engineer (Repair)", "loadouts\ctrg_arid_p_e_rep.sqf"];
this addaction ["Platoon DMR", "loadouts\ctrg_arid_p_dmr.sqf"];
this addaction ["Platoon AR", "loadouts\ctrg_arid_p_ar.sqf"];
this addaction ["Platoon UAV", "loadouts\ctrg_arid_p_uav.sqf"];
this addaction ["Platoon Medic", "loadouts\ctrg_arid_p_medic.sqf"];
this addaction ["Squad Leader", "loadouts\ctrg_arid_sl.sqf"];
this addaction ["Combat Medic", "loadouts\ctrg_arid_medic.sqf"];
this addaction ["Operator Rifle", "loadouts\ctrg_arid_o_r.sqf"];
this addaction ["Operator AR", "loadouts\ctrg_arid_o_ar.sqf"];
this addaction ["Operator Light AT", "loadouts\ctrg_arid_o_lat.sqf"];
this addaction ["Operator MMG", "loadouts\ctrg_arid_o_mmg.sqf"];
this addaction ["Operator Asst. MMG", "loadouts\ctrg_arid_o_mmg_ab.sqf"];
this addaction ["Operator Medium AT", "loadouts\ctrg_arid_o_mat.sqf"];
this addaction ["Operator Asst. Medium AT", "loadouts\ctrg_arid_o_mat_ab.sqf"];
this addaction ["Operator Grenadier", "loadouts\ctrg_arid_o_g.sqf"];
this addaction ["Operator DMR", "loadouts\ctrg_arid_o_dmr.sqf"];
this addaction ["Operator Battlerifle (SCAR-H)", "loadouts\ctrg_arid_o_br.sqf"];
this addaction ["Operator Specialist", "loadouts\ctrg_arid_o_spc.sqf"];
this addaction ["Operator Breacher", "loadouts\ctrg_arid_o_breacher.sqf"];
this addaction ["Operator Engineer (Demo)", "loadouts\ctrg_arid_o_e_demo.sqf"];
this addaction ["Operator Engineer (EOD)", "loadouts\ctrg_arid_o_e_eod.sqf"];
this addaction ["Operator Engineer (Fortification)", "loadouts\ctrg_arid_o_e_fort.sqf"];
this addaction ["Operator Engineer (Repair)", "loadouts\ctrg_arid_o_e_rep.sqf"];
this addaction ["Echo Rifleman", "loadouts\ctrg_arid_e_r.sqf"];
this addaction ["Echo AR", "loadouts\ctrg_arid_e_ar.sqf"];
this addaction ["Echo Engineer (Demo)", "loadouts\ctrg_arid_e_e_demo.sqf"];
this addaction ["Echo Engineer (EOD)", "loadouts\ctrg_arid_e_e_eod.sqf"];
this addaction ["Echo Engineer (Fortification)", "loadouts\ctrg_arid_e_e_fort.sqf"];
this addaction ["Echo Engineer (Repair)", "loadouts\ctrg_arid_e_e_rep.sqf"];
this addaction ["Echo Heavy Weapons (Mortar)", "loadouts\ctrg_arid_e_mor.sqf"];
this addaction ["Echo Asst. Heavy Weapons (Mortar)", "loadouts\ctrg_arid_e_mor_ab.sqf"];
this addaction ["Echo Heavy Weapons (HAT)", "loadouts\ctrg_arid_e_hat.sqf"];
this addaction ["Echo Asst. Heavy Weapons (HAT)", "loadouts\ctrg_arid_e_hat_ab.sqf"];
this addaction ["Fox Commander", "loadouts\ctrg_arid_f_com.sqf"];
this addaction ["Fox Crewman", "loadouts\ctrg_arid_f_crew.sqf"];
this addaction ["Fox Technician", "loadouts\ctrg_arid_f_tech.sqf"];
this addaction ["Rodeo Pilot", "loadouts\pilot_rotaryPilot.sqf"];
this addaction ["Rodeo Co-Pilot (Crewman)", "loadouts\pilot_rotaryPilot.sqf"];
this addaction ["Whiskey Pilot", "loadouts\pilot_fixedWing.sqf"];
this addaction ["<t color=""#0000FF"">" +"Save Loadout", {(_this select 1) setVariable ["SR_Loadout",getUnitLoadout (_this select 1)];}];
this addaction ["<t color=""#0000FF"">" +"Load Loadout", {(_this select 1)  setUnitLoadout ((_this select 1)  getVariable ["SR_Loadout",[]]);}];
