this addaction ["Platoon Leader", "loadouts\baf_pl.sqf"];
this addaction ["Platoon FAC", "loadouts\baf_p_fac.sqf"];
this addaction ["Platoon Engineer (Demo)", "loadouts\baf_p_e_demo.sqf"];
this addaction ["Platoon Engineer (EOD)", "loadouts\baf_p_e_eod.sqf"];
this addaction ["Platoon Engineer (Fortification)", "loadouts\baf_p_e_fort.sqf"];
this addaction ["Platoon Engineer (Repair)", "loadouts\baf_p_e_rep.sqf"];
this addaction ["Platoon DMR", "loadouts\baf_p_dmr.sqf"];
this addaction ["Platoon Driver", "loadouts\baf_p_d.sqf"];
this addaction ["Platoon AR", "loadouts\baf_p_ar.sqf"];
this addaction ["Platoon UAV", "loadouts\baf_p_uav.sqf"];
this addaction ["Platoon Medic", "loadouts\baf_p_medic.sqf"];
this addaction ["Squad Leader", "loadouts\baf_sl.sqf"];
this addaction ["Combat Medic", "loadouts\baf_medic.sqf"];
this addaction ["Operator Rifle", "loadouts\baf_o_r.sqf"];
this addaction ["Operator AR", "loadouts\baf_o_ar.sqf"];
this addaction ["Operator Light AT", "loadouts\baf_o_lat.sqf"];
this addaction ["Operator Light AT (NLAW)", "loadouts\baf_o_lat2.sqf"];
this addaction ["Operator MMG", "loadouts\baf_o_mmg.sqf"];
this addaction ["Operator Asst. MMG", "loadouts\baf_o_mmg_ab.sqf"];
this addaction ["Operator Medium AT", "loadouts\baf_o_mat.sqf"];
this addaction ["Operator Asst. Medium AT", "loadouts\baf_o_mat_ab.sqf"];
this addaction ["Operator Grenadier", "loadouts\baf_o_g.sqf"];
this addaction ["Operator DMR (L86A2 DMR)", "loadouts\baf_o_dmr.sqf"];
this addaction ["Operator Battlerifle (HK417)", "loadouts\baf_o_br.sqf"];
this addaction ["Operator Specialist (L119A1)", "loadouts\baf_o_spc.sqf"];
this addaction ["Operator Breacher", "loadouts\baf_o_breacher.sqf"];
this addaction ["Operator Engineer (Demo)", "loadouts\baf_o_e_demo.sqf"];
this addaction ["Operator Engineer (EOD)", "loadouts\baf_o_e_eod.sqf"];
this addaction ["Operator Engineer (Fortification)", "loadouts\baf_o_e_fort.sqf"];
this addaction ["Operator Engineer (Repair)", "loadouts\baf_o_e_rep.sqf"];
this addaction ["Echo Rifleman", "loadouts\baf_e_r.sqf"];
this addaction ["Echo AR", "loadouts\baf_e_ar.sqf"];
this addaction ["Echo Engineer (Demo)", "loadouts\baf_e_e_demo.sqf"];
this addaction ["Echo Engineer (EOD)", "loadouts\baf_e_e_eod.sqf"];
this addaction ["Echo Engineer (Fortification)", "loadouts\baf_e_e_fort.sqf"];
this addaction ["Echo Engineer (Repair)", "loadouts\baf_e_e_rep.sqf"];
this addaction ["Echo Heavy Weapons (Mortar)", "loadouts\baf_e_mor.sqf"];
this addaction ["Echo Asst. Heavy Weapons (Mortar)", "loadouts\baf_e_mor_ab.sqf"];
this addaction ["Echo Heavy Weapons (HAT)", "loadouts\baf_e_hat.sqf"];
this addaction ["Echo Asst. Heavy Weapons (HAT)", "loadouts\baf_e_hat_ab.sqf"];
this addaction ["Echo Driver", "loadouts\baf_e_d.sqf"];
this addaction ["Fox Commander", "loadouts\baf_f_com.sqf"];
this addaction ["Fox Crewman", "loadouts\baf_f_crew.sqf"];
this addaction ["Fox Technician", "loadouts\baf_f_tech.sqf"];
this addaction ["Sierra Spotter", "loadouts\baf_s_spotter.sqf"];
this addaction ["Sierra Sniper (AWS)", "loadouts\baf_s_sniper.sqf"];
this addaction ["Sierra Sniper (m107)", "loadouts\baf_s_sniper_m107.sqf"];
this addaction ["Sierra Recon", "loadouts\baf_s_recon.sqf"];
this addaction ["<t color=""#0000FF"">" +"Save Loadout", {(_this select 1) setVariable ["SR_Loadout",getUnitLoadout (_this select 1)];}];
this addaction ["<t color=""#0000FF"">" +"Load Loadout", {(_this select 1)  setUnitLoadout ((_this select 1)  getVariable ["SR_Loadout",[]]);}];
