this addaction ["Platoon Leader", "loadouts\f_pl.sqf"];
this addaction ["Platoon FAC", "loadouts\f_p_fac.sqf"];
this addaction ["Platoon Engineer (Demo)", "loadouts\f_p_e_demo.sqf"];
this addaction ["Platoon Engineer (EOD)", "loadouts\f_p_e_eod.sqf"];
this addaction ["Platoon Engineer (Fortification)", "loadouts\f_p_e_fort.sqf"];
this addaction ["Platoon Engineer (Repair)", "loadouts\f_p_e_rep.sqf"];
this addaction ["Platoon DMR", "loadouts\f_p_dmr.sqf"];
this addaction ["Platoon Driver", "loadouts\f_p_d.sqf"];
this addaction ["Platoon AR", "loadouts\f_p_ar.sqf"];
this addaction ["Platoon Medic", "loadouts\f_p_medic.sqf"];
this addaction ["Squad Leader", "loadouts\f_sl.sqf"];
this addaction ["Combat Medic", "loadouts\f_medic.sqf"];
this addaction ["Operator Rifle", "loadouts\f_o_r.sqf"];
this addaction ["Operator AR", "loadouts\f_o_ar.sqf"];
this addaction ["Operator Light AT", "loadouts\f_o_lat.sqf"];
this addaction ["Operator MMG", "loadouts\f_o_mmg.sqf"];
this addaction ["Operator Asst. MMG", "loadouts\f_o_mmg_ab.sqf"];
this addaction ["Operator Medium AT", "loadouts\f_o_mat.sqf"];
this addaction ["Operator Asst. Medium AT", "loadouts\f_o_mat_ab.sqf"];
this addaction ["Operator Grenadier", "loadouts\f_o_g.sqf"];
this addaction ["Operator DMR (5.56)", "loadouts\f_o_dmr.sqf"];
this addaction ["Operator Battlerifle (HK417)", "loadouts\f_o_br.sqf"];
this addaction ["Operator Specialist (SCAR-L)", "loadouts\f_o_spc.sqf"];
this addaction ["Operator Breacher", "loadouts\f_o_breacher.sqf"];
this addaction ["Operator Engineer (Demo)", "loadouts\f_o_e_demo.sqf"];
this addaction ["Operator Engineer (EOD)", "loadouts\f_o_e_eod.sqf"];
this addaction ["Operator Engineer (Fortification)", "loadouts\f_o_e_fort.sqf"];
this addaction ["Operator Engineer (Repair)", "loadouts\f_o_e_rep.sqf"];
this addaction ["Echo Rifleman", "loadouts\f_e_r.sqf"];
this addaction ["Echo AR", "loadouts\f_e_ar.sqf"];
this addaction ["Echo Engineer (Demo)", "loadouts\f_e_e_demo.sqf"];
this addaction ["Echo Engineer (EOD)", "loadouts\f_e_e_eod.sqf"];
this addaction ["Echo Engineer (Fortification)", "loadouts\f_e_e_fort.sqf"];
this addaction ["Echo Engineer (Repair)", "loadouts\f_e_e_rep.sqf"];
this addaction ["Echo Heavy Weapons (Mortar)", "loadouts\f_e_mor.sqf"];
this addaction ["Echo Asst. Heavy Weapons (Mortar)", "loadouts\f_e_mor_ab.sqf"];
this addaction ["Echo Heavy Weapons (HAT)", "loadouts\f_e_hat.sqf"];
this addaction ["Echo Asst. Heavy Weapons (HAT)", "loadouts\f_e_hat_ab.sqf"];
this addaction ["Echo Driver", "loadouts\f_e_d.sqf"];
this addaction ["Sierra Spotter", "loadouts\f_s_spotter.sqf"];
this addaction ["Sierra Sniper", "loadouts\f_s_sniper.sqf"];
this addaction ["Sierra Recon", "loadouts\f_s_recon.sqf"];
this addaction ["Rodeo Pilot", "loadouts\pilot_rotaryPilot.sqf"];
this addaction ["Rodeo Co-Pilot (Crewman)", "loadouts\pilot_rotaryPilot.sqf"];
this addaction ["Whiskey Pilot", "loadouts\pilot_fixedWing.sqf"];
this addaction ["<t color=""#0000FF"">" +"Save Loadout", {(_this select 1) setVariable ["SR_Loadout",getUnitLoadout (_this select 1)];}];
this addaction ["<t color=""#0000FF"">" +"Load Loadout", {(_this select 1)  setUnitLoadout ((_this select 1)  getVariable ["SR_Loadout",[]]);}];
