if (!isServer) exitWith	{};

"air_raid" remoteExec ["playsound",0]; 
sleep 8;
"air_raid" remoteExec ["playsound",0]; 
sleep 8;
"air_raid" remoteExec ["playsound",0]; 
sleep 8;
"air_raid" remoteExec ["playsound",0]; 
sleep 1;
["t1", "Sh_82mm_AMOS", 100, 20, [2,3]] spawn BIS_fnc_fireSupportVirtual;
sleep 1;
["t2", "Sh_82mm_AMOS", 100, 20, [2,3]] spawn BIS_fnc_fireSupportVirtual;
sleep 2;
["t3", "Sh_82mm_AMOS", 100, 20, [2,3]] spawn BIS_fnc_fireSupportVirtual;
sleep 1;
["t4", "Sh_82mm_AMOS", 100, 20, [2,3]] spawn BIS_fnc_fireSupportVirtual;
"air_raid" remoteExec ["playsound",0]; 
sleep 8;
"air_raid" remoteExec ["playsound",0]; 
sleep 8;
"air_raid" remoteExec ["playsound",0]; 
sleep 8;
"air_raid" remoteExec ["playsound",0]; 
sleep 8;
"air_raid" remoteExec ["playsound",0]; 
sleep 8;
"air_raid" remoteExec ["playsound",0]; 
sleep 8;
"air_raid" remoteExec ["playsound",0]; 
start = true;
publicVariable "start";